import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/query";
import { Header } from "@/components/header";

import { setDefaultOptions } from "date-fns/setDefaultOptions";
import { ptBR } from "date-fns/locale";
setDefaultOptions({ locale: ptBR });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </QueryProvider>
    </html>
  );
}
